# Generated by Django 4.2.1 on 2023-05-26 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='client'),
            preserve_default=False,
        ),
    ]
